=== icyphy/accessors/accessors/web/Accessor_1.dtd
<!-- TerraSwarm Level 1 Accessors DTD Version 0.1, http://terraswarm.org -->
<!-- $Id$ -->

<!ELEMENT class (author | description | input | output | require | script | version)*>
<!ATTLIST class
	name CDATA #REQUIRED
    extends CDATA #IMPLIED
    implements CDATA #IMPLIED
>

<!ELEMENT interface (author | description | input | output | require | version)*>
<!ATTLIST class
	name CDATA #REQUIRED
    implements CDATA #IMPLIED
>

<!ELEMENT author (#PCDATA)>

<!ELEMENT description (#PCDATA)>
<!ATTLIST description
	type CDATA #IMPLIED
>

<!ELEMENT input EMPTY>
<!ATTLIST input
	name CDATA #REQUIRED
    type CDATA #IMPLIED
    value CDATA #IMPLIED
    description CDATA #IMPLIED
>

<!ELEMENT output EMPTY>
<!ATTLIST output
	name CDATA #REQUIRED
    type CDATA #IMPLIED
    description CDATA #IMPLIED
>

<!ELEMENT require (#PCDATA)>
<!ATTLIST require
	name CDATA #IMPLIED
>

<!ELEMENT script (#PCDATA)>
<!ATTLIST script
          type CDATA #IMPLIED
>

<!ELEMENT version (#PCDATA)>

=== icyphy/accessors/web/obsolete/StockTick.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="https://www.icyphy.org/accessors/renderHTML.xsl"?>
<!DOCTYPE class PUBLIC "-//TerraSwarm//DTD Accessor 1//EN"
    "https://www.icyphy.org/accessors/obsolete/Accessor_1.dtd">
<class name="StockTick" extends="org.terraswarm.JSAccessor">
  <version>0.1 $Date$</version>
  <author>Edward A. Lee</author>
  <input
    name="symbol"
    value="YHOO"
    type="string"
    description="The stock symbol."/>
  <output
    name="price"
    type="number"
    description="The most recent stock price (bid)."/>       
  <description type="text/html">
    <![CDATA[
This accessor, when fired, reads the most recent trade price for the specified stock symbol from a Yahoo server.
    ]]>
  </description>
  <require name="httpClient"/>
  <script type="text/javascript">
    // <![CDATA[
// This accessor requires the optional 'httpClient' module, which may or may
// not be provided by an accessor host. Most hosts will provide this module.
var http = require('httpClient');

function getPrice() {
    // Read the current value of the 'symbol' input.
    var stock = get('symbol');
    // Construct a URL to obtain a stock price.
    var url = "http://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20yahoo.finance.quotes%20where%20symbol%20in%20(%22"
        + stock
        + "%22)%0A%09%09&env=http%3A%2F%2Fdatatables.org%2Falltables.env&format=json";
    // Request a stock price, and provide a function to handle the response.
    http.get(url, function(response) {
        // Assuming the response is JSON, parse it.
        var json = JSON.parse(response.body);
        // Extract the last trade price from the JSON record.
        var price = parseFloat(json.query.results.quote.LastTradePriceOnly);
        // Send the price to the 'price' output.
        send('price', price);
    });
}

var handle = null;

exports.initialize = function() {
    // Invoke the getPrice function each time a 'symbol' input arrives.
    handle = addInputHandler('symbol', getPrice);
}

exports.wrapup = function() {
    // Failing to do this will likely trigger an exception when the model stops running,
    // because the getPrice() function will attempt to send an output after the model
    // has stopped.
    removeInputHandler(handle, 'symbol');
}
    // ]]>
  </script>
</class>

=== icyphy/accessors/accessors/web/WiiMote.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="renderHTML.xsl"?>
<!DOCTYPE class PUBLIC "-//TerraSwarm//DTD Accessor 1//EN"
    "http://www.terraswarm.org/accessors/Accessor_1.dtd">
<class name="WiiMote" extends="org.terraswarm.kernel.JavaScript">
  <version>0.1</version>
  <author>Edward A. Lee</author>
  <input
    name="rumble"
    value="false"
    type="boolean"
    description="Control to turn on or off the rumble feature."/>
  <output
    name="x"
    type="number"
    description="The x axis acceleration."/>
  <output
    name="y"
    type="number"
    description="The y axis acceleration."/>
  <output
    name="z"
    type="number"
    description="The z axis acceleration."/>
  <documentation type="text/html">
    <![CDATA[
This accessor gets accelerometer data from a Nintendo WiiMote.
The accessor runs out of the box, but the server side requires some setup to publish
the accelerometer readings to an online key-value store.
There is a Ptolemy II model that will do this publishing, but
it is not checked in to Ptolemy II SVN repository, because it includes GPLd
code for the Bluetooth interface.
	]]>
  </documentation>	  
  <script type="text/javascript">
    // <![CDATA[

// State variables.
var wiimote;

function initialize() {
   wiimote = readURL("http://ptango.eecs.berkeley.edu:8077/keyvalue/get?id=wiimote").trim();
   if (! wiimote || wiimote == "nil") {
      error('WiiMote server does not appear to be running.');
   }
   alert("Connecting to wiimote server at " + wiimote);
}

function fire() {
   var result = readURL(wiimote);
   var parsed;
   try {
      parsed = JSON.parse(result);
   } catch (e) {
      // What to do here?
      error("Unexpected result from WiiMote server: " + result);
   }
   send(parsed.x, x);
   send(parsed.y, y);
   send(parsed.z, z);
}

	// ]]>
  </script>
</class>

=== icyphy/accessors/branches/accessors-det-1/web/obsolete/Weather.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="renderHTML.xsl"?>
<!DOCTYPE class PUBLIC "-//TerraSwarm//DTD Accessor 1//EN"
    "https://www.icyphy.org/accessors/obsolete/Accessor_1.dtd">
<class name="Weather" extends="org.terraswarm.JSAccessor">
  <version>0.1 $Date$</version>
  <author>Alex Mead and Edward A. Lee</author>
  <input
    name="longitude"
    value="-122.26"
    type="number"
    description="The longitude of a location (default is Berkeley)."/>
  <input
    name="latitude"
    value="37.85"
    type="number"
    description="The latitude of a location (default is Berkeley)."/>
  <output
    name="temperature"
    type="number"
    description="Temperature in degrees celsius."/>       
  <output
    name="relativeHumidity"
    type="number"
    description="Relative humidity (percent)."/>       
  <output
    name="name"
    type="string"
    description="Name of the location (nearest city name)."/>       
  <output
    name="pressure"
    type="number"
    description="Pressure in hectopascals (hPa), where 1 hPa is 100 pascals."/>       
  <output
    name="windSpeed"
    type="number"
    description="Wind speed (meters per second)."/>       
  <output
    name="windDirection"
    type="number"
    description="Wind source direction (in degrees, relative to north)."/>       
  <description type="text/html">
    <![CDATA[
This accessor, when fired, reads the current weather data from
<a href="http://openweathermap.org">openweathermap.org</a>.
	]]>
  </description>
  <script type="text/javascript">
    // <![CDATA[
	function fire() {
        var lat = get('latitude');
        var lon = get('longitude');
        var url = "http://api.openweathermap.org/data/2.5/weather?lat="
                + lat
                + "&lon=" + lon;
        var record = readURL(url);
        var json = JSON.parse(record);
        var temp = (parseFloat(json.main.temp) - 273.15);
        var humidity = parseFloat(json.main.humidity);
        var pres = parseFloat(json.main.pressure);
        var ws = parseFloat(json.wind.speed);
        var wd = parseFloat(json.wind.deg);
        
        // Send outputs
        send('windDirection', wd);
        send('windSpeed', ws);
        send('name', json.name);
        send('pressure', pres);
        send('temperature', temp);
        send('relativeHumidity', humidity);
	}
	// ]]>
  </script>
</class>

=== icyphy/accessors/web/obsolete/VertxPublish.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="renderHTML.xsl"?>
<!DOCTYPE class PUBLIC "-//TerraSwarm//DTD Accessor 1//EN"
    "https://www.icyphy.org/accessors/obsolete/Accessor_1.dtd">
<class name="VertxPublish" extends="org.terraswarm.JSAccessor">
  <version>0.1 $Date$</version>
  <author>Patricia Derler, Edward A. Lee, Ben Zhang</author>
  <require name="eventbus"/>
  <input
    name="address"
    value="topic"
    type="string"
    description="The event bus address, which is the name of the event stream. This defaults to 'topic'."/>
  <input
    name="message"
    type="JSON"
    description="The message to the bus."/>       
  <input
    name="broadcast"
    value="true"
    type="boolean"
    description="True to broadcast the message to all subscribers. False to send to exactly one subscriber, in a roughly round-robin fashion."/>
  <input
    name="busHost"
    value=""
    type="string"
    description="The name of the network interface to use for the Vert.x event bus. A blank string is interpreted as 'localhost'."/>
  <input
    name="busHostPort"
    value="0"
    type="int"
    description="The port for the Vert.x event bus. A value of 0 indicates to just find an available port."/>
  <output
    name="reply"
    type="JSON"
    description="The reply, if any, received after a point-to-point send (where broadcast == false)."/>
  <description type="text/html">
    <![CDATA[
This accessor publishes to a Vert.x event bus, which is a peer-to-peer publish-and-subscribe system. The published data will be sent to any subscriber that subscribes to the same address and runs in the same Vertx cluster (see the VertxSubscribe accessor). The Vertx cluster normally includes all machines that hear multicast packets sent by the machine hosting this accessor.
<p>
The input to be published can be any data type supported by accessors that has a string representation in JSON syntax. The data will be converted to a string in JSON format and sent to the event bus. The VertxSubscribe accessor will parse that string and output the data in the native format of its host.
</p><p>
If the broadcast input is set to false, then instead of broadcasting the message to all subscribers, the Vertx bus will pick exactly one subscriber and send the message to it.  The bus picks the subscribers in an approximately round-robin fashion. If the subscriber replies to this message, then that will reply (required to be also be a JSON object) will be produced on the reply output port.
</p><p>
The busHost input specifies the name of the network interface through which to connect to the Vert.x event bus cluster, and busHostPort specifies the port to use for this. Normally, you can leave these at their default values unless you need to need to use a network interface that is not 'localhost' or you need to use a particular port. These two inputs are examined only at initialization time, so changing them during execution of a swarmlet will have no effect.
</p>
	]]>
  </description>
  <script type="text/javascript">
    // <![CDATA[
    
var eventbus = require('eventbus');
var bus;
var handle;

exports.initialize = function() {
    var port = get('busHostPort');
    var host = get('busHost');
    bus = new eventbus.VertxBus({'port':port, 'host':host});
    
    handle = addInputHandler('message', function() {
        var topic = get('address');
        var msg = get('message');
        var all = get('broadcast');
        if (msg) {
            if (all) {
                bus.publish(topic, msg);
            } else {
                bus.send(topic, msg, replyHandler);
            }
        }
    });
}

var replyHandler = function(message) {
   send('reply', message);
}

exports.wrapup = function() {
  bus.unsubscribe();
  removeInputHandler(handle, 'message');
}

	//  ]]>
  </script>
</class>

=== icyphy/accessors/accessors/web/VertxSubscribe.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="renderHTML.xsl"?>
<!DOCTYPE class PUBLIC "-//TerraSwarm//DTD Accessor 1//EN"
    "http://www.terraswarm.org/accessors/Accessor_1.dtd">
<class name="VertxSubscribe" extends="org.terraswarm.JSAccessor">
  <version>0.1</version>
  <author>Patricia Derler, Edward A. Lee, Ben Zhang</author>
  <requires name="eventbus"/>
  <input
    name="address"
    value="topic"
    type="string"
    description="The event bus address, or the name of the events to which to subscribe. This defaults to 'topic'."/>
  <output
    name="message"
    description="The message from the bus."/>
  <input
    name="reply"
    value=""
    type="string"
    description="The reply to send back to the sender for point-to-point messages, or the empty string to send no reply."/>
  <input
    name="busHost"
    value=""
    type="string"
    description="The name of the network interface to use for the Vert.x event bus. A blank string is interpreted as 'localhost'."/>
  <input
    name="busHostPort"
    value="0"
    type="int"
    description="The port for the Vert.x event bus. A value of 0 indicates a default port of 25500."/>
  <documentation type="text/html">
    <![CDATA[
    This actor subscribes to a Vert.x event bus on a specified channel.
    The output data type is undeclared, because it depends on what is published
    on the event bus. This implementation assumes that what is published on the event
    bus is a string in JSON format.
    The busHost is the name of the network interface through which to connect to the Vert.x event bus cluster.
    The busHostPort is the port to use for this.
    These two inputs are examined only at initialization time.
	]]>
  </documentation>
  <script type="text/javascript">
    // <![CDATA[
var eventbus = require('eventbus');
var bus;
var currentAddress;

var onReceived = function(msg) {
    send(msg, message);
}

exports.initialize = function() {
    var port = get(busHostPort);
    var host = get(busHost);
    bus = new eventbus.VertxBus({'port':port, 'host':host});
    currentAddress = get(address);
    bus.subscribe(currentAddress);
    bus.on(get(address), onReceived);
    var replyText = get(reply);
    if (replyText) {
        bus.setReply(replyText);
    }
}

addInputHandler(function() {
    var topic = get(address);
    if (topic != currentAddress) {
        bus.unsubscribe(currentAddress);
        bus.subscribe(topic);
    }
}, address);

addInputHandler(function() {
    var replyText = get(reply);
    if (replyText) {
        bus.setReply(replyText);
    } else {
        bus.setReply(null);
    }
}, reply);

exports.wrapup = function() {
    bus.unsubscribe();
}
  	// ]]>
  </script>
</class>

=== icyphy/accessors/accessors/web/WebSocketClient.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="renderHTML.xsl"?>
<!DOCTYPE class PUBLIC "-//TerraSwarm//DTD Accessor 1//EN"
    "http://www.terraswarm.org/accessors/Accessor_1.dtd">
<class name="WebSocketClient" extends="org.terraswarm.JSAccessor">
  <version>0.1</version>
  <author>Hokeun Kim</author>
  <input
    name="url"
    value="ws://localhost:8080"
    type="string"
    description="The url of the web socket server."/>
  <input
    name="data"
    value="Hello, server!"
    type="string"
    description="The data to be sent to the web socket server during the next firing."/>
  <input
    name="enable"
    value="true"
    type="boolean"
    description="When this is set true, this accessor sends the data on firing."/>
  <output
    name="message"
    type="string"
    description="The message received from the web socket server"/>   
  <output
    name="error"
    type="string"
    description="The error string of the connection."/>     
  <output
    name="status"
    type="number"
    description="The status code of the connection. 1: connection established, 0: connection closed, -1: an error occurred."/>
  <requires name="webSocket"/>   
  <documentation type="text/html">
    <![CDATA[
This accessor, when initialized, connects to the web socket server,
when fired, sends the data on the data port,
when wraped up, closes the ongoing connection.
This accessor generates output on the message port when a message is received from the server.
  ]]>
  </documentation>
  <script type="text/javascript">
    // <![CDATA[
  var WebSocket = require('webSocket');
  var opened = false;
  var queue = [];
  function sendDataInQueue() {
    if (opened) {
      var queueLength = queue.length;
      for (var i = 0; i < queueLength; i++) {
        ws.send(queue[i]);
      }
      queue = [];
    }
  }
  function onOpen() {
    print('client: connection to a server established');
    opened = true;
    send(1, status);
    sendDataInQueue();
  }
  function onClose() {
    print('client: connection is closed');
    openend = false;
    send(0, status);
  }
  function onError() {
    print('client: an error occurred.');
    openend = false;
    send(-1, status);
  }
  function onMessage(received, flags) {
    print('client: onMessage');
    if (flags.binary) {
      received = WebSocket.binToStr(received);
    }
    send(received, message);
  }
  var ws = null;
  function initialize() {
    if (ws == null) {
      print('client: connecting to a server');
      ws = new WebSocket.Socket(get(url));
      ws.on('open', onOpen);
      ws.on('message', onMessage);
      ws.on('close', onClose);
      ws.on('error', onError);
    }
  }
  function wrapup() {
    if (ws != null) {
      ws.close();
      print('client: closing the socket');
    }
    opened = false;
  }
  function fire() {
    if (get(enable)) {
      queue.push(get(data));
    }
    sendDataInQueue();
  }
  // ]]>
  </script>
</class>
