=== icyphy/accessors/trunk/accessors/web/Accessor_1.dtd
<!-- TerraSwarm Level 1 Accessors DTD Version 0.1, http://terraswarm.org -->
<!-- $Id: MoML_1.dtd 57539 2010-04-02 00:57:06Z cxh $ -->

<!ELEMENT class (input | output | property | script | documentation | version | author)*>
<!ATTLIST class
	name CDATA #REQUIRED
    extends CDATA #IMPLIED
>

<!ELEMENT author (#PCDATA)>
<!ATTLIST author
	type CDATA #IMPLIED
>

<!ELEMENT documentation (#PCDATA)>
<!ATTLIST documentation
	type CDATA #IMPLIED
>

<!ELEMENT input EMPTY>
<!ATTLIST input
	name CDATA #REQUIRED
    type CDATA #IMPLIED
    value CDATA #IMPLIED
    description CDATA #IMPLIED
>

<!ELEMENT output EMPTY>
<!ATTLIST output
	name CDATA #REQUIRED
    type CDATA #IMPLIED
    description CDATA #IMPLIED
>

<!ELEMENT script (#PCDATA)>
<!ATTLIST script
	type CDATA #IMPLIED
>

<!ELEMENT version (#PCDATA)>
<!ATTLIST version
	type CDATA #IMPLIED
>

=== icyphy/accessors/trunk/accessors/web/WebSocketClient.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="renderHTML.xsl"?>
<!DOCTYPE class PUBLIC "-//TerraSwarm//DTD Accessor 1//EN"
    "http://www.terraswarm.org/accessors/Accessor_1.dtd">
<class name="WebSocketClient" extends="org.terraswarm.JSAccessor">
  <version>0.1</version>
  <author>Hokeun Kim</author>
  <input
    name="url"
    value="ws://localhost:8080"
    type="string"
    description="The url of the web socket server."/>
  <input
    name="data"
    value="Hello, server!"
    type="string"
    description="The data to be sent to the web socket server during the next firing."/>
  <input
    name="enable"
    value="true"
    type="boolean"
    description="When this is set true, this accessor sends the data on firing."/>
  <output
    name="message"
    type="string"
    description="The message received from the web socket server"/>   
  <output
    name="error"
    type="string"
    description="The error string of the connection."/>     
  <output
    name="status"
    type="number"
    description="The status code of the connection. 1: connection established, 0: connection closed, -1: an error occurred."/>
  <requires name="webSocket"/>   
  <documentation type="text/html">
    <![CDATA[
This accessor, when initialized, connects to the web socket server,
when fired, sends the data on the data port,
when wraped up, closes the ongoing connection.
This accessor generates output on the message port when a message is received from the server.
  ]]>
  </documentation>
  <script type="text/javascript">
    // <![CDATA[
  var WebSocket = require('webSocket');
  var opened = false;
  var dataQueue = [];
  var dataQueueIsLocked = false;
  function sendDataInQueue() {
    while (dataQueueIsLocked);
    dataQueueIsLocked = true;
    if (opened) {
      var queueLength = dataQueue.length;
      for (var i = 0; i < queueLength; i++) {
        ws.send(dataQueue[i]);
      }
      dataQueue = [];
    }
    dataQueueIsLocked = false;
  }
  function onOpen() {
    print('client: connection to a server established');
    opened = true;
    send(1, status);
    sendDataInQueue();
  }
  function onClose(message) {
    print('client: connection is closed. ' + message);
    openend = false;
    send(0, status);
  }
  function onError() {
    print('client: an error occurred.');
    openend = false;
    send(-1, status);
  }
  function onMessage(received, flags) {
    print('client: onMessage');
    if (flags.binary) {
      received = WebSocket.binToStr(received);
    }
    send(received, message);
  }
  var ws = null;
  var inputQueue = [];
  function inputHandler() {
    inputQueue.push(get(data));
  }
  function initialize() {
    inputQueue = [];
    addInputHandler(data, inputHandler);
    if (ws == null) {
      print('client: connecting to a server');
      ws = new WebSocket.Socket(get(url));
      ws.on('open', onOpen);
      ws.on('message', onMessage);
      ws.on('close', onClose);
      ws.on('error', onError);
    }
  }
  function wrapup() {
    if (ws != null) {
      ws.close();
      print('client: closing the socket');
    }
    opened = false;
  }
  function fire() {
    if (get(enable)) {
      var queueLength = inputQueue.length;
      for (var i = 0; i < queueLength; i++) {
        dataQueue.push(inputQueue[i]);
      }
      inputQueue = [];
    }
    sendDataInQueue();
  }
  // ]]>
  </script>
</class>

=== icyphy/accessors/trunk/accessors/web/VertxPublish.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="renderHTML.xsl"?>
<!DOCTYPE class PUBLIC "-//TerraSwarm//DTD Accessor 1//EN"
    "http://www.terraswarm.org/accessors/Accessor_1.dtd">
<class name="VertxPublish" extends="org.terraswarm.JSAccessor">
  <version>0.1</version>
  <author>Patricia Derler, Edward A. Lee, Ben Zhang</author>
  <requires name="eventbus"/>
  <input
    name="address"
    value="topic"
    type="string"
    description="The event bus address, which is the name of the event stream. This defaults to 'topic'."/>
  <input
    name="message"
    description="The message to the bus."/>       
  <input
    name="broadcast"
    value="true"
    type="boolean"
    description="True to broadcast the message to all subscribers. False to send to exactly one subscriber, in a roughly round-robin fashion."/>
  <input
    name="busHost"
    value=""
    type="string"
    description="The name of the network interface to use for the Vert.x event bus. A blank string is interpreted as 'localhost'."/>
  <input
    name="busHostPort"
    value="0"
    type="int"
    description="The port for the Vert.x event bus. A value of 0 indicates to just find an available port."/>
  <output
    name="reply"
    type="string"
    description="The reply, if any, received after a point-to-point send (where broadcast == false)."/>
  <documentation type="text/html">
    <![CDATA[
    This accessor publishes to a Vert.x event bus. The input can be any data type
    supported by accessors that has a string representation in JSON syntax. The
    published even will be a string in JSON format.
    <p>
    The busHost is the name of the network interface through which to connect to the Vert.x event bus cluster.
    The busHostPort is the port to use for this.
    These two inputs are examined only at initialization time.
	]]>
  </documentation>
  <script type="text/javascript">
    // <![CDATA[
    
var eventbus = require('eventbus');
var bus;

exports.initialize = function() {
  var port = get(busHostPort);
  var host = get(busHost);
  bus = new eventbus.VertxBus({'port':port, 'host':host});
}

var replyHandler = function(message) {
   send(message, reply);
}

addInputHandler(function() {
  var topic = get(address);
  var msg = get(message);
  var all = get(broadcast);
  if (msg) {
    if (all) {
      bus.publish(topic, JSON.stringify(msg));
    } else {
      bus.send(topic, JSON.stringify(msg), replyHandler);
    }
  }
}, message);

exports.wrapup = function() {
  bus.unsubscribe();
}

	//  ]]>
  </script>
</class>

=== icyphy/accessors/trunk/accessors/web/Hue.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="renderHTML.xsl"?>
<!DOCTYPE entity PUBLIC "-//TerraSwarm//DTD Accessor 1//EN"
    "http://terraswarm.org/accessors/Accessor_1.dtd">
<class name="Hue" extends="org.terraswarm.kernel.JavaScript">
  <version>0.1</version>
  <author>Edward A. Lee</author>
  <input
    name="bridgeID"
    value="1"
    type="number"
    description="The bridge identifier (an integer beginning with 1)."/>
  <input
    name="lightID"
    type="number"
    value="1"
    description="The light identifier (an integer beginning with 1)."/>
  <input
    name="brightness"
    type="number"
    value="255"
    description="The brightness (an integer between 0 and 255)."/>
  <input
    name="hue"
    type="number"
    value="65280"
    description="The hue (an integer between 0 and 65280)."/>
  <input
    name="saturation"
    type="number"
    value="255"
    description="The saturation (an integer between 0 and 255)."/>
  <input
    name="on"
    type="boolean"
    value="false"
    description="Whether the light is on (true) or off (false)."/>
  <input
    name="transitiontime"
    type="number"
    value="4"
    description="The transition time, in multiples of 100ms (an integer between 0 and 65535)."/>
  <documentation type="text/html">
    <![CDATA[
    This accessor controls a Philips Hue lightbulb.
    <p>
    Upon initialization, it retrieves the URL of the bridge
    from a key-value store service (the location of which is currently hardwired into
    the script). It then attempts to access the bridge as a user "ptolemyuser".
    If there is no such user, it registers such a user and requests that the
    link button on the bridge be pushed to authorize registration of this user.
    It then verifies that the specified light is accessible, and if not, provides
    a list of available lights.
    <p>
    When this accessor fires, it sets the parameters of the specified
    light according to the input values.
	]]>
  </documentation>
  <script type="text/javascript">
    // <![CDATA[

// State variables.
var timeout = 3000;
var bridge;
var url;

// Uncormment the following to see the URL being used for the bridge.
// alert("Connecting to: " + bridge);

function initialize() {
   // Find the IP address for the bridge.
   // This accessor assumes that the IP addres of the Hue Bridge is stored on the
   // ptango keyvalue service, indexed by HueBridgeX, where X is the bridgeID of this accessor.
   bridge = readURL("http://ptango.eecs.berkeley.edu:8077/keyvalue/get?id=HueBridge"
      + get(bridgeID)).trim();
   if (! bridge.match("/$")) {
      bridge = bridge + "/";
   }
   // Build up the URL we want one piece at a time, to make sure each piece works.
   url = bridge;

   // First make sure the bridge is actually there and responding.
   try {
      httpRequest(url, "GET", null, "", timeout);
   } catch ( ex) {
      // FIXME: We should do a UPnP discovery here and find a bridge.
      alert("No Hue bridge responding at " + url + "\n" + ex);
   }
   // Next, make sure that "ptolemyuser" is an authorized user.
   url = url + "api/ptolemyuser/";
   var lights = JSON.parse(httpRequest(url, "GET", null, "", timeout));
   if (lights instanceof Array && lights.length > 0 && lights[0].error) {
      var description = lights[0].error.description;
      if (description.match("unauthorized user")) {
         // ptolemyuser is not an authorized user.  Add this user.
         httpRequest(bridge + "api", "POST", null, '{"devicetype":"ptolemyuser", "username":"ptolemyuser"}', timeout);
         alert("Push the link button on the Hue bridge to establish a connection.");
         httpRequest(bridge + "api", "POST", null, '{"devicetype":"ptolemyuser", "username":"ptolemyuser"}', timeout);
         // Check to see whether it succeeded.
         lights = JSON.parse(httpRequest(url, "GET", null, "", timeout));
         if (lights instanceof Array && lights.length > 0 && lights[0].error) {
             var description = lights[0].error.description;
             if (description.match("unauthorized user")) {
                error("Failed to create user.");
             }
         }
      }
   }
   // Next, make sure the specified light is reachable.
   var reachable;
   try {
      reachable = lights.lights[get(lightID)].state.reachable;
   } catch (e) {
      error("Failed to access the state of light "
         + get(lightID) + " at URL " + url + "\n" + e);
   }

   if (! reachable) {
      // Light is not reachable.
      // Find the lights that are reachable.
      var other = "";
      try {
         for (id in lights.lights) {
            if (! lights.lights[id].state.reachable) {
               continue;
            }
            if (other == "") {
               other = " Lights that are reachable are: " + id;
            } else {
               other = other + ", " + id;
            }
         }
         other = other + ".";
      } catch (e) {
         // Ignore and don't give further info about reachable lights.
      }
      error("Light " + get(lightID) + " is not reachable at " + url + other);
   }
   url = url + "lights/" + get(lightID) + "/state";
}

function fire() {
   var command = '{"on":false,';
   if (get(on)) {
      command = '{"on":true,';
   }
   command = command 
         + '"bri":' + limit(get(brightness), 0, 255) + ','
         + '"hue":' + limit(get(hue), 0, 65280) + ','
         + '"sat":' + limit(get(saturation), 0, 255) + ','
         + '"transitiontime":' + limit(get(transitiontime), 0, 65535)
         + '}';
   var response = httpRequest(url, "PUT", null, command, timeout);
   if (response instanceof Array && response.length > 0 && response[0].error) {
       alert(response[0].error.description);
   }
}

// Turn the light off on wrapup.
function wrapup() {
   var command = '{"on":false}';
   var response = httpRequest(url, "PUT", null, command, timeout);
   if (response instanceof Array && response.length > 0 && response[0].error) {
       alert(response[0].error.description);
   }
}

// Utility function to limit the range of a number
// and to force it to be an integer.
function limit(value, low, high) {
   if (value < low) {
      return low;
   } else if (value > high) {
      return high;
   } else {
      return value.toFixed(0);
   }
}
  	// ]]>
  </script>
</class>

=== icyphy/accessors/accessors/web/VertxPublish.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="renderHTML.xsl"?>
<!DOCTYPE class PUBLIC "-//TerraSwarm//DTD Accessor 1//EN"
    "http://www.terraswarm.org/accessors/Accessor_1.dtd">
<class name="VertxPublish" extends="org.terraswarm.JSAccessor">
  <version>0.1</version>
  <author>Patricia Derler, Edward A. Lee, Ben Zhang</author>
  <input
    name="busHost"
    value=""
    type="string"
    description="The name of the network interface to use for the Vert.x event bus. A blank string is interpreted as 'localhost'."/>
  <input
    name="busHostPort"
    value="0"
    type="string"
    description="The port for the Vert.x event bus. A value of 0 indicates a default port of 25500."/>
  <input
    name="address"
    value=""
    type="string"
    description="The event bus address, which is the name of the event stream."/>
  <input
    name="message"
    description="The message to the bus."/>       
  <requires name="eventbus"/>
  <documentation type="text/html">
    <![CDATA[
    This accessor publishes to a Vert.x event bus. The input can be any data type
    supported by accessors that has a string representation in JSON syntax. The
    published even will be a string in JSON format.
    <p>
    The busHost is the name of the network interface through which to connect to the Vert.x event bus cluster.
    The busHostPort is the port to use for this.
    These two inputs are examined only at initialization time.
	]]>
  </documentation>
  <script type="text/javascript">
    // <![CDATA[
    
var eventbus = require('eventbus');
var bus;

exports.initialize = function() {
  var port = get(busHostPort);
  var host = get(busHost);
  bus = new eventbus.VertxBus({'port':port, 'host':host});
}

addInputHandler(function() {
  var topic = get(address);
  var msg = get(message);
  if (msg) {
    bus.publish(topic, JSON.stringify(msg));
  }
}, message);

exports.wrapup = function() {
  bus.unsubscribe();
}

	//  ]]>
  </script>
</class>

=== icyphy/accessors/trunk/accessors/web/VertxSubscribe.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="renderHTML.xsl"?>
<!DOCTYPE class PUBLIC "-//TerraSwarm//DTD Accessor 1//EN"
    "http://www.terraswarm.org/accessors/Accessor_1.dtd">
<class name="VertxSubscribe" extends="org.terraswarm.JSAccessor">
  <version>0.1</version>
  <author>Patricia Derler, Edward A. Lee, Ben Zhang</author>
  <input
    name="busHost"
    value="localhost"
    type="string"
    description="The IP address or DNS name of the host for the Vert.x bus server."/>
  <input
    name="busHostPort"
    value="8080"
    type="string"
    description="The port for the host for the Vert.x bus."/>
  <input
    name="address"
    value=""
    type="string"
    description="The event bus address, or the name of the events to which to subscribe."/>
  <output
    name="message"
    type="string"
    description="The message from the bus, as a JSON-encoded string."/>
  <requires name="vertxEventBus"/>
  <documentation type="text/html">
    <![CDATA[
    This actor subscribes to a Vert.x event bus.
	]]>
  </documentation>
  <script type="text/javascript">
    // <![CDATA[

var Vertx = require('vertxEventBus');
var eb = null;
var connectTries = 0;
var maxTries = 5;
var retryDelay = 2000;  // 2 seconds
var opened = false;

function onOpen() {
  opened = true;
  eb.registerAddressListener(get(address), 
        function onReceived(msg) {
            send(msg, message);
        });
}

exports.initialize = function() {
    if (eb == null) { 
        connectTries = 1;       
        eb = new Vertx.VertxBus({host: get(busHost), port: get(busHostPort)});
        eb.on('open', onOpen);
        eb.on('error', function(kind) {
           // Upon connection error, try to connect again after 1 second, up to 3 times
           if (kind != null && kind == 'connect') {
              if (connectTries < maxTries) {
                 setTimeout(function() {
                    connectTries++;
                   eb.connect();
                 }, retryDelay);
              } else {
                 // TODO:  How should the accessor signal an error?
                 // Create a "status" output port?  Throw an exception?  Call wrapup()?
                 print("Subscriber cannot connect to the event bus.");
              }
           }
        });
    }
}

exports.wrapup = function() {
    if (opened) {
       eb.close();
    }
    eb = null;
}
	// 
   ]]>
  </script>
</class>
